Eventor/Models/App/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Eventor.Models.App
{
    public class Item
    {
        public int ItemId { get; set; }

        public int PedidoId { get; set; }

        [Required]
        public int EntradaId { get; set; }

        public decimal Precio { get; set; }

        public int Cantidad { get; set; }

        public decimal Subtotal { get; set; }

        public virtual Entrada Entrada { get; set; }

        public virtual Pedido Pedido { get; set; }
    }
}

Eventor/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eventor.Models.App;

namespace Eventor.Controllers
{
    public class ItemsController : Controller
    {
        EventorDbContext db = new EventorDbContext();

        public ActionResult Index()
        {
            var Items = (List<Item>)Session["Items"];
            if (Items == null)
                Items = new List<Item>();
            return View(Items);
        }

        // Se llama con Ajax desde AddToCart.js
        public ActionResult AddItemToCart(int entradaId, int cantidad, decimal precio)
        {
            try
            {
                Entrada entrada = db.Entradas.Find(entradaId);

                var Items = (List<Item>)Session["Items"];

                if (Items == null)
                    Items = new List<Item>();

                bool Encontrada = false;

                foreach (Item item in Items)
                {
                    if (item.Entrada.EntradaId == entradaId)
                    {
                        item.Cantidad += cantidad;

                        if (item.Cantidad > entrada.CantidadMaxima)
                            item.Cantidad = entrada.CantidadMaxima;

                        Encontrada = true;
                    }
                }
                if (!Encontrada)
                    Items.Add(new Item()
                    {
                        EntradaId = entradaId,
                        Entrada = entrada,
                        Cantidad = cantidad,
                        Precio = precio,
                        Subtotal = precio * cantidad
                    });

                Session["Items"] = Items;

                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        public ActionResult ClearSession()
        {
            if (Session["Items"] != null)
                Session["Items"] = null;
            return RedirectToAction("Index");
        }

        public ActionResult DeleteFromCart(int id)
        {
            var items = (List<Item>)Session["Items"];
            if (items != null)
            {
                items.Remove(items.Where(i => i.Entrada.EntradaId == id).First());
                Session["Items"] = items;
            }
                
            return RedirectToAction("Index");
        }
    }
}

Eventor/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eventor.Models.App;
using Microsoft.AspNet.Identity;

namespace Eventor.Controllers
{
    [Authorize(Roles = "Participante")]
    public class PedidosController : Controller
    {
        EventorDbContext db = new EventorDbContext();
        
        public ActionResult Index()
        {
            var username = User.Identity.GetUserName();
            return View(db.Pedidos.Where(p => p.UserName == username).OrderByDescending(p => p.FechaHora).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.Items = pedido.Items.ToList();

            return View(pedido);
        }

        public ActionResult FinalizarCompra()
        {
            using (var db = new EventorDbContext())
            {
                var items = (List<Item>)Session["Items"];

                if (items != null)
                {
                    decimal total = 0;
                    foreach (var item in items)
                    {
                        total += item.Subtotal;
                    }

                    var pedido = new Pedido ()
                    {
                        FechaHora = DateTime.Now,
                        UserName = User.Identity.GetUserName(),
                        Total = total
                    };
                    
                    db.Pedidos.Add(pedido);
                    db.SaveChanges();

                    db.Entry(pedido).State = EntityState.Detached;

                    int id = int.Parse(db.Pedidos
                            .OrderByDescending(p => p.FechaHora)
                            .Select(r => r.PedidoId)
                            .First().ToString());

                    var pedidoAgregado = db.Pedidos.Find(id);
                    Participante participante = null;
                    var user = User.Identity.GetUserName();

                    foreach (var item in items)
                    {
                        pedidoAgregado.Items.Add(new Item
                        {
                            Cantidad = item.Cantidad,
                            EntradaId = item.EntradaId,
                            PedidoId = id,
                            Subtotal = item.Subtotal,
                            Precio = item.Precio
                        });

                        participante = db.Participantes.Where(p=>p.EventoId == item.Entrada.EventoId && p.Correo == user).Single();
                        participante.Estado = Estado.Confirmado;
                        db.Entry(participante).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

Eventor/Views/Items/Index.cshtml
@model IEnumerable<Eventor.Models.App.Item>

@{
    ViewBag.Title = "Index";
}

<br />
<div class="well">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <h3><strong>Carrito de Compras</strong></h3>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="btn-group btn-group-lg pull-right">
                @if (Model.Count() > 0)
                {
                    @Html.ActionLink("Comprar", "FinalizarCompra", "Pedidos", null, new { @class = "btn btn-primary" })
                }
                @Html.ActionLink("Limpiar todo", "ClearSession", null, new { @class = "btn btn-default" })
            </div>

        </div>
    </div>
</div>
<br />

<table class="table table-bordered table-hover">
    <tr>
        <th>
            Entrada
        </th>
        <th>
            Evento
        </th>
        <th>
            Cantidad
        </th>
        <th>
            Quitar
        </th>
    </tr>

    @if (Model.Count() > 0)
    {
        foreach (var item in Model)
        {
            <tr class="success">
                <td>
                    @Html.DisplayFor(modelItem => item.Entrada.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Entrada.Evento.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.ActionLink("Quitar", "DeleteFromCart", new { id = item.EntradaId })
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td class="warning text-center" colspan="4">No hay elementos en el carrito</td>
        </tr>
    }

</table>