Eventor/Models/App/Entrada.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Eventor.Models.App
{
    public class Entrada
    {
        public int EntradaId { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Longitud máxima: 50 caracteres")]
        public string Nombre { get; set; }

        [Required]
        [Range(0,9999,ErrorMessage="El precio debe ser mayor o igual a cero")]
        [DisplayFormat(DataFormatString="{0:C}")]
        public decimal Precio { get; set; }

        [Required]
        [Range(1,100,ErrorMessage="La entrada debe cubrir a una persona como mínimo")]
        public int Cupo { get; set; }

        [Display(Name = "Cantidad Mínima")]
        [Required]
        [Range(1, 100, ErrorMessage = "La cantidad mínima es una unidad")]
        public int CantidadMinima { get; set; }

        [Display(Name = "Cantidad Máxima")]
        [Range(1, 100, ErrorMessage = "La cantidad máxima es 100 unidades")]
        public int CantidadMaxima { get; set; }

        [Required]
        public string Descripcion { get; set; }

        [Required]
        public int EventoId { get; set; }

        public virtual Evento Evento { get; set; }
    }
}

Eventor/Controllers/EntradasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eventor.Models.App;

namespace Eventor.Controllers
{
    public class EntradasController : Controller
    {
        private EventorDbContext db = new EventorDbContext();

        [Authorize(Roles = "Organizador, Participante")]
        public ActionResult Index(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            var evento = db.Eventos.Where(ev => ev.EventoId == id).Single();
            var entradas = evento.Entradas;

            ViewBag.NombreEvento = evento.Nombre;
            ViewBag.ConteoEntradas = evento.Entradas.Count();
            ViewBag.Finalizado = evento.Final.CompareTo(DateTime.Now) < 0;

            if (User.IsInRole("Organizador"))
                return View(entradas.ToList());
            else
                return View("Buy", entradas.ToList());
        }

        // GET: Entradas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entrada entrada = db.Entradas.Find(id);
            if (entrada == null)
            {
                return HttpNotFound();
            }
            ViewBag.NombreEvento = entrada.Evento.Nombre;
            return View(entrada);
        }

        // GET: Entradas/Create
        public ActionResult Create(int id)
        {
            ViewBag.EventoId = id;
            ViewBag.NombreEvento = db.Eventos.Find(id).Nombre;
            return View();
        }

        // POST: Entradas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EntradaId,Nombre,Precio,Cupo,CantidadMinima,CantidadMaxima,Descripcion,FechaLimite,EventoId")] Entrada entrada)
        {
            if (ModelState.IsValid)
            {
                db.Entradas.Add(entrada);
                db.SaveChanges();
                return RedirectToAction("Index", new { @id = entrada.EventoId});
            }

            ViewBag.EventoId = entrada.EventoId;
            return View(entrada);
        }

        // GET: Entradas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Entrada entrada = db.Entradas.Find(id);

            if (entrada == null)
            {
                return HttpNotFound();
            }

            ViewBag.EventoId = entrada.EventoId;
            ViewBag.NombreEvento = db.Eventos.Find(entrada.EventoId).Nombre;
            
            return View(entrada);
        }

        // POST: Entradas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EntradaId,Nombre,Precio,Cupo,CantidadMinima,CantidadMaxima,Descripcion,FechaLimite,EventoId")] Entrada entrada)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entrada).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { @id = entrada.EventoId });
            }
            return View(entrada);
        }

        // GET: Entradas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entrada entrada = db.Entradas.Find(id);
            if (entrada == null)
            {
                return HttpNotFound();
            }
            ViewBag.NombreEvento = entrada.Evento.Nombre;
            return View(entrada);
        }

        // POST: Entradas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entrada entrada = db.Entradas.Find(id);
            db.Entradas.Remove(entrada);
            db.SaveChanges();
            return RedirectToAction("Index", new { @id = entrada.EventoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eventor/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eventor.Models.App;
using Microsoft.AspNet.Identity;

namespace Eventor.Controllers
{
    public class EventosController : Controller
    {
        private EventorDbContext db = new EventorDbContext();

        [Authorize(Roles = "Organizador")]
        // GET: Eventos
        public ActionResult Index()
        {

            var username = User.Identity.GetUserName();

            var eventos = db.Eventos.Where(e=> e.UserName == username).Include(e => e.Contacto).OrderByDescending(e=>e.Inicio);

            return View(eventos.ToList());
        }
        [Authorize(Roles = "Participante, Organizador")]
        public ActionResult Explorar()
        {
            if (User.IsInRole("Organizador"))
            {
                return RedirectToAction("Index");
            }
            else
            {
                var usuario = User.Identity.GetUserName();
                var eventos = db.Eventos.ToList();
                var ProximosEventos = new List<Evento>();
                var EventosHistoricos = new List<Evento>();

                foreach (var evento in eventos)
                    if (evento.Participantes.Any(p => p.Correo == usuario))
                    {
                        if (DateTime.Compare(evento.Final, DateTime.Now) > 0)
                            ProximosEventos.Add(evento);
                        else
                            EventosHistoricos.Add(evento);
                    }
                ViewBag.ProximosEventos = ProximosEventos;
                ViewBag.EventosHistoricos = EventosHistoricos;

                return View(eventos);
            }
        }
        [Authorize(Roles = "Organizador, Participante")]
        // GET: Eventos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }

            ViewBag.Invitados = evento.Participantes.Count();
            ViewBag.Confirmados = evento.Participantes.Where(e => e.Estado == Estado.Confirmado).Count();
            ViewBag.Cancelados = evento.Participantes.Where(e => e.Estado == Estado.Cancelado).Count();
            ViewBag.Finalizado = evento.Final.CompareTo(DateTime.Now) < 0;
            ViewBag.EntradasVendidas = 0;
            ViewBag.Ingresos = 0;


            var items = db.Items.Where(i=>i.Entrada.EventoId == id).ToList();

            if (items != null)
            {
                var total = items.Sum(i => i.Subtotal);

                var cantidad = items.Sum(i => i.Cantidad);

                ViewBag.EntradasVendidas = cantidad;
                ViewBag.Ingresos = total;
            }
            
            Session["EventoId"] = id;

            return View(evento);
        }
        
        [Authorize(Roles = "Organizador")]
        // GET: Eventos/Create
        public ActionResult Create()
        {
            var modelo = new CrearEventoModelo();
            ViewBag.UserName = User.Identity.GetUserName();
            return View(modelo);
        }

        // POST: Eventos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Organizador")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CrearEventoModelo modelo)
        {
            var contacto = modelo.Contacto;
            var evento = modelo.Evento;

            if (modelo.Evento.Inicio.CompareTo(modelo.Evento.Final) > 0)
                ModelState.AddModelError("", "La fecha de inicio debe ser menor que la fecha final");

            if (ModelState.IsValid)
            {
                evento.Contacto = contacto;
                evento.UserName = User.Identity.GetUserName();
                db.Eventos.Add(evento);
                db.SaveChanges();
                return RedirectToAction("Details", new { @id = evento.EventoId });
            }
            return View(modelo);
        }
        [Authorize(Roles = "Organizador")]
        // GET: Eventos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var modelo = new CrearEventoModelo();
            modelo.Evento =  db.Eventos.Find(id);
            if (modelo.Evento == null)
            {
                return HttpNotFound();
            }
            modelo.Contacto = modelo.Evento.Contacto;

            return View(modelo);
        }
        [Authorize(Roles = "Organizador")]
        // POST: Eventos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CrearEventoModelo modelo)
        {
            if (modelo.Evento.Inicio.CompareTo(modelo.Evento.Final) > 0)
                ModelState.AddModelError("", "La fecha de inicio debe ser menor que la fecha final");
            
            if (ModelState.IsValid)
            {
                db.Entry(modelo.Contacto).State = EntityState.Modified;
                db.SaveChanges();

                modelo.Evento.ContactoId = modelo.Contacto.ContactoId;

                db.Entry(modelo.Evento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { @id = modelo.Evento.EventoId });
            }
            return View(modelo);
        }
        [Authorize(Roles = "Organizador")]
        // GET: Eventos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }
        [Authorize(Roles = "Organizador")]
        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evento evento = db.Eventos.Find(id);
            db.Eventos.Remove(evento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eventor/Views/Entradas/Buy.cshtml
@model IEnumerable<Eventor.Models.App.Entrada>
@using Eventor.Models;
@{
    ViewBag.Title = "Comprar entradas";
    
}

<br />
<div class="well">
    <div class="row">
        <div class="col-md-8">
            <h3><strong>@ViewBag.NombreEvento - Comprar entradas</strong></h3>
        </div>
        <div class="col-md-4">
            <div class="btn-group btn-group-lg pull-right">
                @Html.ActionLink("Volver", "Details","Eventos", new { @id = ViewContext.RouteData.Values["id"] }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

<br />
<div class="row">
    @if(Model.Any())
    {
        foreach (var item in Model)
        {
            <div class="col-md-4 col-xs-12">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-8">
                                <h4 class="panel-title"><strong>@Html.DisplayFor(modelItem => item.Nombre)</strong></h4>
                            </div>
                            <div class="col-xs-4">
                                <h4 class="panel-title"><strong>@Html.DisplayFor(modelItem => item.Precio)</strong></h4>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">

                        <p><strong>Cupo:</strong> @Html.DisplayFor(modelItem => item.Cupo) personas</p>
                        <p><strong>Descripción:</strong> @Html.DisplayFor(modelItem => item.Descripcion)</p>


                    </div>
                    <div class="panel-footer">

                        @if ((bool)ViewBag.Finalizado)
                        {
                            <input type="button" value="Añadir al carrito" class="btn btn-success" disabled/>
                        }
                        else
                        {
                            <a href="#"
                               class="btn btn-success AddCart"
                               @*data-toggle="modal"
                               data-target="#myModal"*@
                               data-preciounitario="@Html.DisplayFor(modelItem => item.Precio)"
                               data-ventamax="@Html.DisplayFor(modelItem => item.CantidadMaxima)"
                               data-ventamin="@Html.DisplayFor(modelItem => item.CantidadMinima)"
                               data-entradaid="@Html.DisplayFor(modelItem => item.EntradaId)"
                               data-url="@Url.Action("AddItemToCart","Items")">
                                Añadir al carrito
                            </a>
                        }
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="alert alert-warning">
            No existen entradas para este evento aún
        </div>
    }

</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Seleccione la cantidad de entradas</h4>
            </div>
            <div class="modal-body">
                <form class="form-inline" role="form">
                    <label for="Cantidad">Cantidad de entradas:</label>
                    <div class="form-group">
                        <select id="Cantidad" class="form-control"></select>
                    </div>
                </form>
                <p class="text-right">
                    <strong>Precio unitario: </strong><label id="PrecioUnitario"></label>
                </p>
                <hr />
                <p class="text-right">
                    <strong>Subtotal: </strong><label id="Subtotal"></label>
                </p>
                
            </div>
            <div class="modal-footer">
                <div class="btn-group">
                    <button type="button" class="btn btn-primary" id="btnAgregarAlCarrito">
                        Agregar al carrito
                        <img src="~/Content/img/ajax-loader.gif" id="ImgLoader" width="16" height="16" hidden />
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
                
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/AddToCart")
}

Eventor/Views/Entradas/Create.cshtml
@model Eventor.Models.App.Entrada

@{
    ViewBag.Title = "Crear Entrada";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Hidden("EventoId", (int)ViewBag.EventoId)

        <br />
        <div class="well">
            <div class="row">
                <div class="col-md-8">
                    <h3><strong>@ViewBag.NombreEvento - Crear una entrada</strong></h3>
                </div>
                <div class="col-md-4">
                    <div class="btn-group btn-group-lg pull-right">
                        <input type="submit" value="¡Publicar Entrada!" class="btn btn-lg btn-primary" />
                        @Html.ActionLink("Volver", "Index", new { @id = ViewContext.RouteData.Values["id"]}, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Información General<span class="glyphicon glyphicon-list pull-right"></span></h4>
                </div>
                <div class="panel-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cupo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cupo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cupo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CantidadMinima, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CantidadMinima, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CantidadMinima, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CantidadMaxima, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CantidadMaxima, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CantidadMaxima, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}   

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryDateTimePicker")
}

Eventor/Views/Entradas/Delete.cshtml
@model Eventor.Models.App.Entrada

@{
    ViewBag.Title = "Eliminar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    <div class="well">
        <div class="row">
            <div class="col-md-6">
                <h3><strong>@ViewBag.NombreEvento - Eliminar entrada</strong></h3>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-lg pull-right">
                    <input type="submit" value="Eliminar" class="btn btn-lg btn-danger" />
                    @Html.ActionLink("Volver", "Index", new { @id = Model.EventoId }, new { @class = "btn btn-default" })
                </div>

            </div>
        </div>
    </div>
}

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>¿Desea eliminar la siguiente entrada?<span class="glyphicon glyphicon-user pull-right"></span></h4>
        </div>
        <div class="panel-body">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>
                <hr />
                <dt>
                    @Html.DisplayNameFor(model => model.Precio)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Precio)
                </dd>
                <hr />
                <dt>
                    @Html.DisplayNameFor(model => model.Cupo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Cupo)
                </dd>
                <hr />
                <dt>
                    @Html.DisplayNameFor(model => model.CantidadMinima)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CantidadMinima)
                </dd>
                <hr />
                <dt>
                    @Html.DisplayNameFor(model => model.CantidadMaxima)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CantidadMaxima)
                </dd>
                <hr />
                <dt>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descripcion)
                </dd>

            </dl>

        </div>
    </div>
</div>

Eventor/Views/Entradas/Index.cshtml
@model IEnumerable<Eventor.Models.App.Entrada>

@{
    ViewBag.Title = "Administrar Entradas";
}
   <br /> 
<div class="well">
    <div class="row">
        <div class="col-md-8">
            <h3><strong>@ViewBag.NombreEvento - Administrar @ViewBag.ConteoEntradas entrada(s)</strong></h3>
        </div>
        <div class="col-md-4">
            <div class="btn-group btn-group-lg pull-right">
                
                @if(!(bool)ViewBag.Finalizado)
                {
                    @Html.ActionLink("Crear", "Create", new { @id = ViewContext.RouteData.Values["id"] }, new { @class = "btn btn-primary" })
                }
                @Html.ActionLink("Volver", "Details","Eventos", new { @id = ViewContext.RouteData.Values["id"] }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

    <table class="table table-bordered table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cupo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadMinima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadMaxima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            @if (!(bool)ViewBag.Finalizado)
            {
                <th>
                    Acción
                </th>
            }
        </tr>

        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cupo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadMinima)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadMaxima)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    @if (!(bool)ViewBag.Finalizado)
                    {
                        <td class="text-center">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="@Url.Action("Edit","Entradas", new { id = item.EntradaId })" class="btn btn-default">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                    <span class="sr-only">Editar</span>
                                </a>

                                <a href="@Url.Action("Details","Entradas", new { id = item.EntradaId })" class="btn btn-default">
                                    <i class="glyphicon glyphicon-list-alt"></i>
                                    <span class="sr-only">Ver</span>
                                </a>

                                <a href="@Url.Action("Delete","Entradas", new { id = item.EntradaId })" class="btn btn-default">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    <span class="sr-only">Eliminar</span>
                                </a>
                            </div>
                        </td>
                    }
                </tr>
            }
        }
        else
        {
            <tr>
                <td class="warning text-center" colspan="7">
                    Aún no se han creado entradas para este evento
                </td>
            </tr>
        }

    </table>